### PR TITLE
Fix and significantly speed up the destroy script

### LINKED ISSUE #141: Destroy functionality is broken
## Type of Issue:

- [x] Bug: Something isn't working
- [ ] Enhancement: New feature or request
- [ ] Question: Further information is requested (I have a question)

#### Issue Creator Checklist

- [x] The appropriate label (bug, enhancement, question) has been attached to this issue.
- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## What's broken?

#140 broke the destroy functionality.  When a branch is deleted, the logic to set the branch_name in the destroy workflow does not work.  It resolves to master, always.  
If you look closely at the code, you can see we moved from github.event.ref to GITHUB_REF.  

## What's the impact of this bug?

When the destroy workflow is triggered, it will always try to run against the master branch.
The destroy fails, as we have several guards against destroying important branches.
End result:  you're unable to destroy environments when deleting a branch.

## Assorted Notes/Considerations

N/A

## AC:

- Destroy functionality is fixed and functioning properly.

### PR DESCRIPTION
**Pull request by mdial89f**
## Purpose

This changeset fixes a bug (introduced by bucket versioning #274) with the destroy script, and speeds things up signifcantly.

#### Linked Issues to Close

Closes #141 
Bug Fix against / related to:  #274 

## Approach

As stated in the linked issue, bucket versioning broke the destroy functionality.  
These changes modify how buckets are emptied prior to cloudformation stacks being removed.  Now, the script removes all object versions and delete markers, a requirement to delete the bucket.

While working on this, I changed the way this script discovered buckets.  Previously, the script found all buckets, then looked for those with a STAGE tag that matched the target stage.  Tags can only be found by making calls for an individual bucket, which meant the script took a long time to run.  Now, the script iterates over the target cloudformation stages and searches for any AWS::S3::Bucket resources.  This is a simpler and much faster operation.

## Learning

N/A

## Assorted Notes/Considerations

This is a bug against the bucket versioning PR.  As such, I'm adding the 'Compliance' label to this PR, so it will surface in searches for the compliance related versioning PR.

#### Pull Request Creator Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [x] This PR meets all acceptance criteria for those issues.
- [x] This PR and linked issue(s) are adequately documented
- [x] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [x] Someone has been assigned this PR.
- [x] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [x] This PR meets all acceptance criteria for those issues.
- [x] This PR and linked issue(s) are adequately documented
- [x] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

### CODE REVIEW

**Review by dwhitecl — APPROVED** [review]

**Comment by dwhitecl** [comment]
via this bug we probably have some orphaned buckets ... if so are we just gonna manually clean them up?

**Comment by dwhitecl** [comment]
also we should add this PR as a comment to the PR that resolves bucket versioning. folks that reference that pr to pull changes into their repo will need this

**Comment by mdial89f** [comment]
> via this bug we probably have some orphaned buckets ... if so are we just gonna manually clean them up?

I apologize, I only saw these after merge.  This was done before hand.  It was orphaned buckets and orphaned stacks, all gone now.

**Comment by mdial89f** [comment]
> also we should add this PR as a comment to the PR that resolves bucket versioning. folks that reference that pr to pull changes into their repo will need this

Done

**Pull request merged**
