### PR TITLE
Update UI src

### PR DESCRIPTION
**Pull request by benjaminpaige**
## Purpose

There will be another pr to follow from this ticket:
[https://qmacbis.atlassian.net/browse/OY2-11915](https://qmacbis.atlassian.net/browse/OY2-11915)

But wanted to keep this pr to a manageable size.

The changes to the ui-src service represented in this pr include:
- Updating packages
- Migrating components based on those updates
- Adding Branded Footer
- Adding Branded Headers
- Correct Layout styling
- Simplify stylesheets
- Update routing comp
- Add Breadcrumbs component
- Update existing tests
- Add unit tests for components

#### Pull Request Creator Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [x] This PR meets all acceptance criteria for those issues.
- [x] This PR and linked issue(s) are adequately documented
- [x] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [x] Someone has been assigned this PR.
- [x] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

### CODE REVIEW

**Comment by benjaminpaige** [comment]
@mdial89f opening this pr for your review, let me know if you want to go over it. also, is there anyway i can mark some of these codeclimate things as wont fix?

**Comment by mdial89f** [comment]
> @mdial89f opening this pr for your review, let me know if you want to go over it. also, is there anyway i can mark some of these codeclimate things as wont fix?

Not sure who can vs who can't. Try to follow the CC link. See if you have the perms to wontfix stuff. 

Im fine with wontfixing the lot of it. Looks like most if not all is from something else and not this change

**Comment by benjaminpaige** [comment]
> > @mdial89f opening this pr for your review, let me know if you want to go over it. also, is there anyway i can mark some of these codeclimate things as wont fix?
> 
> Not sure who can vs who can't. Try to follow the CC link. See if you have the perms to wontfix stuff.
> 
> Im fine with wontfixing the lot of it. Looks like most if not all is from something else and not this change

Yeah i dont think i have permissions. No options present themselves that would allow that.

**Comment by mdial89f** [comment]
> > > @mdial89f opening this pr for your review, let me know if you want to go over it. also, is there anyway i can mark some of these codeclimate things as wont fix?
> > 
> > Not sure who can vs who can't. Try to follow the CC link. See if you have the perms to wontfix stuff.
> > 
> > Im fine with wontfixing the lot of it. Looks like most if not all is from something else and not this change
> 
> Yeah i dont think i have permissions. No options present themselves that would allow that. 

Ok I wontfixed them. 
Can you add me as a reviewer, add the PR to the project board (right hand side, near where you add reviewers), and remove italicized comments.  I'm on my phone, I rarely use the actual GH app, so if any of that is already done I apologize

**Comment by benjaminpaige** [comment]
> > > > @mdial89f opening this pr for your review, let me know if you want to go over it. also, is there anyway i can mark some of these codeclimate things as wont fix?
> > > 
> > > 
> > > Not sure who can vs who can't. Try to follow the CC link. See if you have the perms to wontfix stuff.
> > > Im fine with wontfixing the lot of it. Looks like most if not all is from something else and not this change
> > 
> > 
> > Yeah i dont think i have permissions. No options present themselves that would allow that.
> 
> Ok I wontfixed them. Can you add me as a reviewer, add the PR to the project board (right hand side, near where you add reviewers), and remove italicized instructions. I'm on my phone, I rarely use the actual GH app, so if any of that is already done I apologize

Cool, I added you as a reviewer and added to the project board, but i'm not sure what you mean by remove italicized instructions?

**Review by mdial89f — APPROVED** [review]

**Comment by mdial89f** [comment]
hey just for next time... keep the headings in the PR template.   that format, those sections, have worked alright for us.

**Pull request merged**
